export const projectData: Record<string, { name: string; description: string }[]> = {
  restaurant: [
    { name: "JavaScript", description: "JavaScript ile interaktif bir site tasarımı yapabilirsiniz." },
    { name: "TypeScript", description: "TypeScript ile hata yakalamayı kolaylaştırarak büyük projeler geliştirebilirsiniz." },
    { name: "React", description: "React kullanarak dinamik ve hızlı bir restoran sitesi yapabilirsiniz." },
    { name: "Next.js", description: "Next.js ile SEO dostu ve hızlı bir restoran web sitesi oluşturabilirsiniz." },
    { name: "Tailwind CSS", description: "Tailwind CSS ile şık ve modern bir arayüz tasarlayabilirsiniz." },
    { name: "Node.js", description: "Node.js ile hızlı ve verimli bir backend oluşturabilirsiniz." },
    { name: "Express.js", description: "Express.js ile RESTful API'ler geliştirebilirsiniz." },
  ],
  "hava durumu": [
    { name: "Python", description: "Python ve Flask ile hava durumu API'si oluşturabilirsiniz." },
    { name: "JavaScript", description: "JavaScript ve OpenWeather API ile web tabanlı hava durumu uygulaması yapabilirsiniz." },
    { name: "React Native", description: "React Native ile mobil hava durumu uygulaması yapabilirsiniz." },
    { name: "Django", description: "Django ile güçlü bir hava durumu servisi oluşturabilirsiniz." },
    { name: "Node.js", description: "Node.js ile hava durumu verilerini işleyebilir ve sunabilirsiniz." },
  ],
  "mobil uygulama": [
    { name: "React Native", description: "React Native ile çapraz platform (iOS & Android) uygulamalar geliştirebilirsiniz." },
    { name: "Flutter", description: "Flutter ile hızlı ve güzel mobil uygulamalar geliştirebilirsiniz." },
    { name: "Swift", description: "Swift ile iOS uygulamaları geliştirebilirsiniz." },
    { name: "Kotlin", description: "Kotlin ile Android uygulamaları geliştirebilirsiniz." },
    { name: "Firebase", description: "Firebase ile kullanıcı doğrulama ve veritabanı yönetimi yapabilirsiniz." },
    { name: "Redux", description: "Redux ile uygulamanızın durumunu yönetebilirsiniz." },
  ],
  "e-ticaret": [
    { name: "Shopify", description: "Shopify ile hızlı bir şekilde e-ticaret sitesi oluşturabilirsiniz." },
    { name: "Magento", description: "Magento ile büyük ölçekli e-ticaret projeleri geliştirebilirsiniz." },
    { name: "React", description: "React ile özelleştirilebilir bir e-ticaret arayüzü oluşturabilirsiniz." },
    { name: "Next.js", description: "Next.js ile SEO uyumlu e-ticaret siteleri yapabilirsiniz." },
    { name: "Stripe API", description: "Stripe API ile güvenli ödeme işlemleri gerçekleştirebilirsiniz." },
    { name: "Node.js", description: "Node.js ile ödeme süreçleri ve sipariş yönetimi gerçekleştirebilirsiniz." },
    { name: "MongoDB", description: "MongoDB ile ürün ve kullanıcı verilerini depolayabilirsiniz." },
  ],
  "blog sitesi": [
    { name: "WordPress", description: "WordPress ile kolayca bir blog sitesi oluşturabilirsiniz." },
    { name: "Gatsby", description: "Gatsby ile statik ve hızlı bir blog oluşturabilirsiniz." },
    { name: "Next.js", description: "Next.js ile dinamik ve SEO dostu bir blog hazırlayabilirsiniz." },
    { name: "Markdown", description: "Markdown kullanarak içeriklerinizi kolayca yönetebilirsiniz." },
    { name: "GraphQL", description: "GraphQL ile içerik verilerini verimli bir şekilde alabilirsiniz." },
  ],
  "oyun geliştirme": [
    { name: "Unity", description: "Unity ile 2D ve 3D oyunlar geliştirebilirsiniz." },
    { name: "Unreal Engine", description: "Unreal Engine ile yüksek kaliteli oyunlar oluşturabilirsiniz." },
    { name: "Godot", description: "Godot ile açık kaynaklı oyunlar yapabilirsiniz." },
    { name: "C#", description: "C# kullanarak Unity için oyun kodlayabilirsiniz." },
    { name: "C++", description: "C++ ile Unreal Engine'de güçlü oyunlar geliştirebilirsiniz." },
    { name: "Blender", description: "Blender ile oyunlar için 3D modeller oluşturabilirsiniz." },
    { name: "Photon", description: "Photon ile çok oyunculu oyunlar geliştirebilirsiniz." },
  ],
  "sağlık takip uygulaması": [
    { name: "React Native", description: "React Native ile sağlık takip uygulaması yapabilirsiniz." },
    { name: "Flutter", description: "Flutter ile mobil sağlık uygulaması oluşturabilirsiniz." },
    { name: "Node.js", description: "Node.js ile sağlık verilerini yönetebilirsiniz." },
    { name: "MongoDB", description: "MongoDB ile hasta verilerini güvenli bir şekilde saklayabilirsiniz." },
    { name: "Firebase", description: "Firebase ile kullanıcı yönetimi ve sağlık verisi takibi yapabilirsiniz." },
    { name: "Redux", description: "Redux ile uygulama durumunu yönetebilirsiniz." },
  ],
  "finans uygulaması": [
    { name: "React", description: "React ile modern bir finans yönetim arayüzü oluşturabilirsiniz." },
    { name: "Django", description: "Django ile güçlü bir finans uygulaması geliştirebilirsiniz." },
    { name: "PostgreSQL", description: "PostgreSQL ile güvenli finans verileri saklayabilirsiniz." },
    { name: "Blockchain", description: "Blockchain kullanarak güvenli ödeme sistemleri geliştirebilirsiniz." },
    { name: "Stripe API", description: "Stripe API ile güvenli ödeme sistemleri oluşturabilirsiniz." },
    { name: "Node.js", description: "Node.js ile ödeme işlemleri ve finans verilerini yönetebilirsiniz." },
  ],
  "sosyal medya uygulaması": [
    { name: "React", description: "React ile sosyal medya arayüzü oluşturabilirsiniz." },
    { name: "Firebase", description: "Firebase ile kullanıcı yönetimi ve gerçek zamanlı veri iletimi yapabilirsiniz." },
    { name: "GraphQL", description: "GraphQL ile verileri hızlıca çekebilir ve güncelleyebilirsiniz." },
    { name: "Node.js", description: "Node.js ile sosyal medya platformunun backend'ini oluşturabilirsiniz." },
  ],
  "reklam ağı": [
    { name: "Google Ads API", description: "Google Ads API ile reklam kampanyaları yönetebilirsiniz." },
    { name: "Node.js", description: "Node.js ile reklam verilerini ve kullanıcı etkileşimlerini işleyebilirsiniz." },
    { name: "React", description: "React ile kullanıcı dostu reklam arayüzleri oluşturabilirsiniz." },
    { name: "MongoDB", description: "MongoDB ile reklam verilerini ve kullanıcı etkileşimlerini saklayabilirsiniz." },
  ],
  "not alma uygulaması": [
    { name: "React", description: "React ile interaktif bir not alma uygulaması geliştirebilirsiniz." },
    { name: "Firebase", description: "Firebase ile kullanıcı verilerini güvenli bir şekilde saklayabilirsiniz." },
    { name: "Redux", description: "Redux ile uygulama durumunu yönetebilirsiniz." },
    { name: "Markdown", description: "Markdown kullanarak notlarınızı düzenleyebilir ve stilize edebilirsiniz." },
  ],
};
