export const projectData: Record<string, { name: string; description: string }[]> = { 
  restaurant: [
    { name: "JavaScript", description: "You can design an interactive website using JavaScript." },
    { name: "TypeScript", description: "You can develop large projects more easily by catching errors with TypeScript." },
    { name: "React", description: "You can build a dynamic and fast restaurant site using React." },
    { name: "Next.js", description: "You can create SEO-friendly and fast restaurant websites using Next.js." },
    { name: "Tailwind CSS", description: "You can design a sleek and modern interface using Tailwind CSS." },
    { name: "Node.js", description: "You can create a fast and efficient backend with Node.js." },
    { name: "Express.js", description: "You can develop RESTful APIs with Express.js." },
  ],
  "weather app": [
    { name: "Python", description: "You can create a weather API using Python and Flask." },
    { name: "JavaScript", description: "You can build a web-based weather application using JavaScript and OpenWeather API." },
    { name: "React Native", description: "You can create a mobile weather app using React Native." },
    { name: "Django", description: "You can build a powerful weather service with Django." },
    { name: "Node.js", description: "You can process and serve weather data using Node.js." },
  ],
  "mobile app": [
    { name: "React Native", description: "You can build cross-platform (iOS & Android) applications with React Native." },
    { name: "Flutter", description: "You can develop fast and beautiful mobile applications with Flutter." },
    { name: "Swift", description: "You can build iOS applications with Swift." },
    { name: "Kotlin", description: "You can develop Android applications with Kotlin." },
    { name: "Firebase", description: "You can manage user authentication and database using Firebase." },
    { name: "Redux", description: "You can manage your application's state with Redux." },
  ],
  "e-commerce": [
    { name: "Shopify", description: "You can quickly create an e-commerce site using Shopify." },
    { name: "Magento", description: "You can develop large-scale e-commerce projects with Magento." },
    { name: "React", description: "You can create a customizable e-commerce frontend using React." },
    { name: "Next.js", description: "You can build SEO-friendly e-commerce sites using Next.js." },
    { name: "Stripe API", description: "You can implement secure payment transactions using Stripe API." },
    { name: "Node.js", description: "You can manage payment processes and order management using Node.js." },
    { name: "MongoDB", description: "You can store product and user data with MongoDB." },
  ],
  "blog site": [
    { name: "WordPress", description: "You can easily create a blog site using WordPress." },
    { name: "Gatsby", description: "You can build a static and fast blog with Gatsby." },
    { name: "Next.js", description: "You can create a dynamic and SEO-friendly blog using Next.js." },
    { name: "Markdown", description: "You can easily manage your content using Markdown." },
    { name: "GraphQL", description: "You can fetch content data efficiently using GraphQL." },
  ],
  "game development": [
    { name: "Unity", description: "You can develop 2D and 3D games with Unity." },
    { name: "Unreal Engine", description: "You can create high-quality games with Unreal Engine." },
    { name: "Godot", description: "You can build open-source games with Godot." },
    { name: "C#", description: "You can write game code for Unity using C#." },
    { name: "C++", description: "You can develop powerful games with Unreal Engine using C++." },
    { name: "Blender", description: "You can create 3D models for games using Blender." },
    { name: "Photon", description: "You can develop multiplayer games with Photon." },
  ],
  "health tracking app": [
    { name: "React Native", description: "You can build a health tracking app using React Native." },
    { name: "Flutter", description: "You can create a mobile health application with Flutter." },
    { name: "Node.js", description: "You can manage health data using Node.js." },
    { name: "MongoDB", description: "You can securely store patient data using MongoDB." },
    { name: "Firebase", description: "You can manage users and track health data using Firebase." },
    { name: "Redux", description: "You can manage application state with Redux." },
  ],
  "finance app": [
    { name: "React", description: "You can create a modern finance management interface with React." },
    { name: "Django", description: "You can develop a powerful finance application with Django." },
    { name: "PostgreSQL", description: "You can store secure finance data using PostgreSQL." },
    { name: "Blockchain", description: "You can develop secure payment systems using Blockchain." },
    { name: "Stripe API", description: "You can create secure payment systems using Stripe API." },
    { name: "Node.js", description: "You can manage payment processes and financial data with Node.js." },
  ],
  "social media app": [
    { name: "React", description: "You can build a social media interface with React." },
    { name: "Firebase", description: "You can manage users and real-time data transmission with Firebase." },
    { name: "GraphQL", description: "You can quickly fetch and update data using GraphQL." },
    { name: "Node.js", description: "You can build the backend of a social media platform with Node.js." },
  ],
  "advertising network": [
    { name: "Google Ads API", description: "You can manage advertising campaigns using Google Ads API." },
    { name: "Node.js", description: "You can process advertising data and user interactions with Node.js." },
    { name: "React", description: "You can build user-friendly advertising interfaces with React." },
    { name: "MongoDB", description: "You can store advertising data and user interactions with MongoDB." },
  ],
  "note-taking app": [
    { name: "React", description: "You can develop an interactive note-taking application with React." },
    { name: "Firebase", description: "You can securely store user data with Firebase." },
    { name: "Redux", description: "You can manage application state with Redux." },
    { name: "Markdown", description: "You can organize and style your notes using Markdown." },
  ],
};
